Repository SamarthTech/python-projects-2024, pull requests merged in 2024-10, with the labels that each got.

#5 pacman
  pacman/LISENCE.md
  pacman/README.md
  pacman/game.py
Labels: hacktoberfest

#6 Add real-time speech recognition and translation system with speech-to-speech output
  Translation-speaker/.idea/.gitignore
  Translation-speaker/.idea/inspectionProfiles/Project_Default.xml
  Translation-speaker/.idea/inspectionProfiles/profiles_settings.xml
  Translation-speaker/.idea/language_translation_app.iml
  Translation-speaker/.idea/misc.xml
  Translation-speaker/.idea/modules.xml
  Translation-speaker/README.md
  Translation-speaker/main.py
  Translation-speaker/translated_audio.mp3
  Translation-speaker/translator_app.py
Labels: hacktoberfest, hacktoberfest-accepted

#7 Added a Digital Clock
  Digital Clock/DigitalClock.py
Labels: hacktoberfest, hacktoberfest-accepted

#9 Add Python calculator
  Python Calculator/Python Calculator codes.txt
  Python Calculator/calculator.py
Labels: hacktoberfest, hacktoberfest-accepted

#14 Create Number_Guessing_Game.py
  Number_Guessing_Game/Number_Guessing_Game.py
Labels: open-odyssey, dino-accepted

#15 ToDoList
  ToDoList/ToDoList-main/Assets/Blank
  ToDoList/ToDoList-main/Assets/bg_1.jpg
  ToDoList/ToDoList-main/Assets/bg_1.png
  ToDoList/ToDoList-main/Assets/btn_snd.wav
  ToDoList/ToDoList-main/Assets/icon.ico
  ToDoList/ToDoList-main/Assets/icon.png
  ToDoList/ToDoList-main/Assets/user_data.xlsx
  ToDoList/ToDoList-main/installer.py
  ToDoList/ToDoList-main/main_1.py
Labels: dino-accepted

#19 Library Management System
  Library Management System/.idea/.gitignore
  Library Management System/.idea/.name
  Library Management System/.idea/Project.iml
  Library Management System/.idea/inspectionProfiles/profiles_settings.xml
  Library Management System/.idea/misc.xml
  Library Management System/.idea/modules.xml
  Library Management System/.idea/vcs.xml
  Library Management System/Initial.py
  Library Management System/Library_Management.py
  Library Management System/README.txt
  Library Management System/Search_Combobox.py
  Library Management System/Tables.py
  Library Management System/__pycache__/Library_Management.cpython-311.pyc
  Library Management System/__pycache__/Search_Combobox.cpython-311.pyc
  Library Management System/__pycache__/Tables.cpython-311.pyc
  Library Management System/__pycache__/graph_income.cpython-311.pyc
  Library Management System/graph_income.py
  Library Management System/librarymngt2.1.jpg
  Library Management System/librarymngt3.2.jpg
  Library Management System/librarymngt4.1.jpg
  Library Management System/om
Labels: good first issue, open-odyssey, dino-accepted

#22 Added Plagiarism Detector
  Plagiarism-detector-main/LICENSE
  Plagiarism-detector-main/README.md
  Plagiarism-detector-main/__init__.py
  Plagiarism-detector-main/example_document.txt
  Plagiarism-detector-main/feature_extraction.py
  Plagiarism-detector-main/main.py
  Plagiarism-detector-main/preprocess.py
  Plagiarism-detector-main/reference1.txt
  Plagiarism-detector-main/reference2.txt
  Plagiarism-detector-main/requirements.txt
  Plagiarism-detector-main/similarity_calculation.py
Labels: open-odyssey, dino-accepted

#23 password_generator
  password_generator/README.md
  password_generator/main.py
Labels: dino-accepted

#27 Snake Game
  Snake Game/Read Me.txt
  Snake Game/Snake Game.py
Labels: good first issue, dino-accepted

#26 blackjack-game
  Blackjack/.idea/.gitignore
  Blackjack/.idea/.name
  Blackjack/.idea/Blackjack.iml
  Blackjack/.idea/inspectionProfiles/profiles_settings.xml
  Blackjack/.idea/misc.xml
  Blackjack/.idea/modules.xml
  Blackjack/.idea/vcs.xml
  Blackjack/README.txt
  Blackjack/main.py
Labels: open-odyssey, dino-accepted

#28 Hangman Game
  Hangman Game/hang.py
Labels: open-odyssey, dino-accepted

#29 AI-controlled snake using BFS and A* pathfinding
  snake-game-ai/.gitattributes
  snake-game-ai/.gitignore
  snake-game-ai/LICENSE
  snake-game-ai/README.md
  snake-game-ai/main.py
Labels: dino-accepted

#30 caeser_cipher
  caeser_cipher/__pycache__/art.cpython-312.pyc
  caeser_cipher/__pycache__/art.cpython-38.pyc
  caeser_cipher/art.py
  caeser_cipher/main.py
Labels: open-odyssey, dino-accepted

#31 Draw with your keyboard
  drwaing-slate/main.py
Labels: open-odyssey, dino-accepted

#32 BlackJack Game
  blackjack-game/main.py
Labels: dino-accepted

#34 Rock Paper Scissors
  Rock Paper Scissor/main.py
Labels: dino-accepted

#35 Stock Price Predictor
  stock-price-predictor/LICENSE
  stock-price-predictor/README.md
  stock-price-predictor/data/download_stock_data.py
  stock-price-predictor/decision_tree_predictor.py
  stock-price-predictor/image.png
  stock-price-predictor/image1.png
  stock-price-predictor/lstm_predictor.py
  stock-price-predictor/main.py
  stock-price-predictor/requirements.txt
  stock-price-predictor/stock_data.csv
  stock-price-predictor/utils/data_preprocessing.py
  stock-price-predictor/utils/model_evaluation.py
Labels: open-odyssey, dino-accepted

#36 Stone-Paper-Scissors
  stone-paper-scissor/.idea/.gitignore
  stone-paper-scissor/.idea/.name
  stone-paper-scissor/.idea/inspectionProfiles/profiles_settings.xml
  stone-paper-scissor/.idea/misc.xml
  stone-paper-scissor/.idea/modules.xml
  stone-paper-scissor/.idea/stone-paper-scissor.iml
  stone-paper-scissor/.idea/vcs.xml
  stone-paper-scissor/README.txt
  stone-paper-scissor/main.py
Labels: open-odyssey, dino-accepted

#38 Added a chatbot built on python and streamlit
  Simple AI Chatbot/.env
  Simple AI Chatbot/Readme.MD
  Simple AI Chatbot/main.py
Labels: open-odyssey, dino-accepted

#44 Add Snake Game (Snake Dash)
  Snake_Game(Snake_Dash)/Font/PoetsenOne-Regular.ttf
  Snake_Game(Snake_Dash)/Graphics/Trophie.png
  Snake_Game(Snake_Dash)/Graphics/apple.png
  Snake_Game(Snake_Dash)/Graphics/body_bl.png
  Snake_Game(Snake_Dash)/Graphics/body_br.png
  Snake_Game(Snake_Dash)/Graphics/body_horizontal.png
  Snake_Game(Snake_Dash)/Graphics/body_tl.png
  Snake_Game(Snake_Dash)/Graphics/body_tr.png
  Snake_Game(Snake_Dash)/Graphics/body_vertical.png
  Snake_Game(Snake_Dash)/Graphics/head_down.png
  Snake_Game(Snake_Dash)/Graphics/head_left.png
  Snake_Game(Snake_Dash)/Graphics/head_right.png
  Snake_Game(Snake_Dash)/Graphics/head_up.png
  Snake_Game(Snake_Dash)/Graphics/tail_down.png
  Snake_Game(Snake_Dash)/Graphics/tail_left.png
  Snake_Game(Snake_Dash)/Graphics/tail_right.png
  Snake_Game(Snake_Dash)/Graphics/tail_up.png
  Snake_Game(Snake_Dash)/Images/game_over.jpg
  Snake_Game(Snake_Dash)/Images/welcome.jpg
  Snake_Game(Snake_Dash)/SnakeGame.py
  Snake_Game(Snake_Dash)/Sound/crunch.wav
  Snake_Game(Snake_Dash)/Sound/game_over.wav
  Snake_Game(Snake_Dash)/high_score.txt
Labels: open-odyssey, dino-accepted

#45 pong game using python
  pong-game/Pong Game/__pycache__/ball.cpython-312.pyc
  pong-game/Pong Game/__pycache__/paddle.cpython-312.pyc
  pong-game/Pong Game/__pycache__/score_board.cpython-312.pyc
  pong-game/Pong Game/__pycache__/table_boundary.cpython-312.pyc
  pong-game/Pong Game/ball.py
  pong-game/Pong Game/paddle.py
  pong-game/Pong Game/pong_game.py
  pong-game/Pong Game/score_board.py
  pong-game/Pong Game/table_boundary.py
Labels: open-odyssey, dino-accepted

#43 Added Tetris game AI in Python
  tetris-game-ai/.gitattributes
  tetris-game-ai/.gitignore
  tetris-game-ai/LICENSE
  tetris-game-ai/README.md
  tetris-game-ai/ai.py
  tetris-game-ai/game.py
  tetris-game-ai/main.py
Labels: open-odyssey, dino-accepted

#48 MysteryRooms Game added
  Mystery Rooms/file.py
Labels: dino-accepted

#49 Snake Game
  Snake Game/Snake Game.py
  Snake Game/snake.py
Labels: dino-accepted

#52 Added initial version of Tea-Making Game with regional tea recipes and feedback system with some added features for now.
  Tea Making Fun Game/Fun _Game(Tea).py
Labels: good first issue, open-odyssey, dino-accepted

#53 Implementing a Python-Based News Reader Application with External Bro…
  Feeds-Reader/rss_reader.py
Labels: open-odyssey, dino-accepted

#54 Play True or False quiz
  play-quiz/Quiz/__pycache__/question_modules.cpython-312.pyc
  play-quiz/Quiz/question_modules.py
  play-quiz/Quiz/quiz.py
Labels: open-odyssey, dino-accepted

#55 21 Game
  21 Game/21 Game
  Rock Paper Scissors/Rock Paper Scissors
Labels: open-odyssey, dino-accepted

#59 Mapping West Bengal Districts On Blank Map
  map-pointing/Map pointing/$districts_names_to_learn$.csv
  map-pointing/Map pointing/District_Datas.csv
  map-pointing/Map pointing/WB_outline_map.gif
  map-pointing/Map pointing/data_collection.py
  map-pointing/Map pointing/main.py
Labels: open-odyssey, dino-accepted

#62 Retro Battleship Game
  Retro Battleship Game/hahaha.png
  Retro Battleship Game/main.py
  Retro Battleship Game/opponentpaceship.png
  Retro Battleship Game/player_bullet2.png
  Retro Battleship Game/spaceship.png
Labels: open-odyssey, dino-accepted

#63 Add Rock, Paper, Scissors with GUI
  Rock, Paper, Scissors with GUI/Font/Haettenschweiler-Regular.ttf
  Rock, Paper, Scissors with GUI/Images/logo.png
  Rock, Paper, Scissors with GUI/Images/paper.png
  Rock, Paper, Scissors with GUI/Images/rock.png
  Rock, Paper, Scissors with GUI/Images/scissors.png
  Rock, Paper, Scissors with GUI/rock, paper, scissors.py
Labels: open-odyssey, dino-accepted

#65 Speak The Meaning Of The Word
  Speak The Meaning Of The Word/Speak The Meaning Of The Word.py
Labels: dino-accepted

#66 diabetes_prediction_using_django
  Diabetes Prediction/diabetes_prediction/.idea/.gitignore
  Diabetes Prediction/diabetes_prediction/.idea/diabetes_prediction.iml
  Diabetes Prediction/diabetes_prediction/.idea/inspectionProfiles/Project_Default.xml
  Diabetes Prediction/diabetes_prediction/.idea/inspectionProfiles/profiles_settings.xml
  Diabetes Prediction/diabetes_prediction/.idea/misc.xml
  Diabetes Prediction/diabetes_prediction/.idea/modules.xml
  Diabetes Prediction/diabetes_prediction/README.md
  Diabetes Prediction/diabetes_prediction/db.sqlite3
  Diabetes Prediction/diabetes_prediction/diabetes.csv
  Diabetes Prediction/diabetes_prediction/diabetes_model.pkl
  Diabetes Prediction/diabetes_prediction/diabetes_prediction/__init__.py
  Diabetes Prediction/diabetes_prediction/diabetes_prediction/__pycache__/__init__.cpython-311.pyc
  Diabetes Prediction/diabetes_prediction/diabetes_prediction/__pycache__/settings.cpython-311.pyc
  Diabetes Prediction/diabetes_prediction/diabetes_prediction/__pycache__/urls.cpython-311.pyc
  Diabetes Prediction/diabetes_prediction/diabetes_prediction/__pycache__/wsgi.cpython-311.pyc
  Diabetes Prediction/diabetes_prediction/diabetes_prediction/asgi.py
  Diabetes Prediction/diabetes_prediction/diabetes_prediction/settings.py
  Diabetes Prediction/diabetes_prediction/diabetes_prediction/urls.py
  Diabetes Prediction/diabetes_prediction/diabetes_prediction/wsgi.py
  Diabetes Prediction/diabetes_prediction/manage.py
  Diabetes Prediction/diabetes_prediction/predictor/__init__.py
  Diabetes Prediction/diabetes_prediction/predictor/__pycache__/__init__.cpython-311.pyc
  Diabetes Prediction/diabetes_prediction/predictor/__pycache__/admin.cpython-311.pyc
  Diabetes Prediction/diabetes_prediction/predictor/__pycache__/apps.cpython-311.pyc
  Diabetes Prediction/diabetes_prediction/predictor/__pycache__/forms.cpython-311.pyc
  Diabetes Prediction/diabetes_prediction/predictor/__pycache__/models.cpython-311.pyc
  Diabetes Prediction/diabetes_prediction/predictor/__pycache__/urls.cpython-311.pyc
  Diabetes Prediction/diabetes_prediction/predictor/__pycache__/views.cpython-311.pyc
  Diabetes Prediction/diabetes_prediction/predictor/admin.py
  Diabetes Prediction/diabetes_prediction/predictor/apps.py
  Diabetes Prediction/diabetes_prediction/predictor/forms.py
  Diabetes Prediction/diabetes_prediction/predictor/migrations/__init__.py
  Diabetes Prediction/diabetes_prediction/predictor/migrations/__pycache__/__init__.cpython-311.pyc
  Diabetes Prediction/diabetes_prediction/predictor/models.py
  Diabetes Prediction/diabetes_prediction/predictor/tests.py
  Diabetes Prediction/diabetes_prediction/predictor/urls.py
  Diabetes Prediction/diabetes_prediction/predictor/views.py
  Diabetes Prediction/diabetes_prediction/templates/predict.html
  Diabetes Prediction/diabetes_prediction/templates/result.html
  Diabetes Prediction/diabetes_prediction/train_model.py
Labels: good first issue, open-odyssey, dino-accepted

#70 Car Detection using OpenCV
  Car image detection/cars.jpg
  Car image detection/cars.xml
  Car image detection/main.py
  Car image detection/readme.md
  Car image detection/requirements.txt
Labels: open-odyssey, dino-accepted

#72 Tic Tac Toe game
  Tic Tac Toe game/Readme.md
  Tic Tac Toe game/main.py
Labels: dino-accepted

#78 Weather app GUI
  Weather-App/README.md
  Weather-App/main.py
Labels: open-odyssey, dino-accepted

#79 Added Particle-simulator with Real-Time Plotting
  Particle-simulator/main.py
Labels: open-odyssey, dino-accepted

#80 added a temperature convertor
  Temperature-Convertor/new.py
Labels: dino-accepted

#82 Add Dice Roller with GUI
  Dice Roller with GUI/Dice Roller with GUI.py
  Dice Roller with GUI/Readme.md
  Dice Roller with GUI/dice/dice1.png
  Dice Roller with GUI/dice/dice2.png
  Dice Roller with GUI/dice/dice3.png
  Dice Roller with GUI/dice/dice4.png
  Dice Roller with GUI/dice/dice5.png
  Dice Roller with GUI/dice/dice6.png
Labels: open-odyssey, dino-accepted

#84 Temperature Convertor
  Temperature Convertor/temperatureConvertor.py
Labels: dino-accepted

#85 Added Bulk Files Renamer in Python
  rename-files-in-python/LICENSE
  rename-files-in-python/README.md
  rename-files-in-python/Screenshot 2024-10-17 122547.png
  rename-files-in-python/main.py
Labels: dino-accepted

#86 Potato Disease Classification using Machine Learning
  Potato Disease Classification/Potatoes Disease Classification Training.ipynb
  Potato Disease Classification/README.md
  Potato Disease Classification/app.py
  Potato Disease Classification/index.html
  Potato Disease Classification/model.h5
  Potato Disease Classification/requirements.txt
Labels: open-odyssey, dino-accepted

#102 Quiz Game
  Expense Tracker/expenses.json
  Expense Tracker/main.py
  QUIZ/main.py
Labels: open-odyssey, dino-accepted

#104 Added emotion-pulse
  emotion-pulse/LICENSE
  emotion-pulse/README.md
  emotion-pulse/emotions.txt
  emotion-pulse/graph.png
  emotion-pulse/main.py
  emotion-pulse/main_nltk.py
  emotion-pulse/read.txt
  emotion-pulse/requirements.txt
  emotion-pulse/settings.py
  emotion-pulse/twitter_analysis.py
Labels: open-odyssey, dino-accepted

#105 added license-plate-detection
  license-plate-detection/Car Images/1.jpg
  license-plate-detection/Car Images/2.jpg
  license-plate-detection/Car Images/3.jpg
  license-plate-detection/Car Images/4.jpg
  license-plate-detection/Car Images/5.jpg
  license-plate-detection/Car Images/6.jpg
  license-plate-detection/Car Images/7.jpg
  license-plate-detection/Car Images/8.jpg
  license-plate-detection/Car Images/9.jpg
  license-plate-detection/Cropped Images-Text/1.jpg
  license-plate-detection/Cropped Images-Text/11.png
  license-plate-detection/Cropped Images-Text/2.jpeg
  license-plate-detection/Cropped Images-Text/3.jpg
  license-plate-detection/Cropped Images-Text/4.jpg
  license-plate-detection/Cropped Images-Text/5.jpg
  license-plate-detection/Cropped Images-Text/6.png
  license-plate-detection/Cropped Images-Text/7.png
  license-plate-detection/LICENSE
  license-plate-detection/README.md
  license-plate-detection/main.py
  license-plate-detection/requirements.txt
Labels: open-odyssey, dino-accepted

#115 Added Plagiarism Checker in Python
  Plagiarism-Checker/Arthur.txt
  Plagiarism-Checker/Ben.txt
  Plagiarism-Checker/Clark.txt
  Plagiarism-Checker/main.py
  Plagiarism-Checker/requirements.txt
Labels: open-odyssey, dino-accepted

#109 added Song Lyrics Extractor
  song-lyrics-extractor/LICENSE
  song-lyrics-extractor/README.md
  song-lyrics-extractor/main.py
  song-lyrics-extractor/requirements.txt
Labels: open-odyssey, dino-accepted

#111 added Currency Converter
  currency-converter/LICENSE
  currency-converter/README.md
  currency-converter/data.txt
  currency-converter/image.png
  currency-converter/main.py
  currency-converter/myapp.conf
  currency-converter/requirements.txt
Labels: open-odyssey, dino-accepted

#113 added Hash Cracker: Multi-threaded Password Cracker
  hash-cracker/LICENSE
  hash-cracker/README.md
  hash-cracker/main.py
Labels: open-odyssey, dino-accepted

#114 added IP Address Finder
  find-ip-address/LICENSE
  find-ip-address/README.md
  find-ip-address/main.py
Labels: open-odyssey, dino-accepted

#118 added Python Dictionary App
  python-dictionary-app/LICENSE
  python-dictionary-app/README.md
  python-dictionary-app/main.py
Labels: open-odyssey, dino-accepted

#120 added PDF to Audio Converter
  pdf-to-audio-converter/LICENSE
  pdf-to-audio-converter/README.md
  pdf-to-audio-converter/demo.pdf
  pdf-to-audio-converter/main.py
Labels: open-odyssey, dino-accepted

#121 Added Duplicate File Remover in Python
  Duplicate-file-remover/README.md
  Duplicate-file-remover/main.py
Labels: open-odyssey, dino-accepted

#127 Added FB Birthday Bot
  FB-Birthday-Bot/README.md
  FB-Birthday-Bot/main.py
Labels: open-odyssey, dino-accepted

#123 Added Text to morse code in Python
  Text-to-morse-code/README.md
  Text-to-morse-code/main.py
  Text-to-morse-code/requirements.txt
Labels: open-odyssey, dino-accepted

#119 added Restaurant Management System
  restaurant-management-system/LICENSE
  restaurant-management-system/README.md
  restaurant-management-system/main.py
Labels: open-odyssey, dino-accepted

#117 added Internet Speed Tool
  InternetSpeedTool/LICENSE
  InternetSpeedTool/README.md
  InternetSpeedTool/main.py
Labels: open-odyssey, dino-accepted

#116 Added Image to ASCII in Python
  Image-to-ASCII/Suzume.png
  Image-to-ASCII/ascii_img.txt
  Image-to-ASCII/main.py
  Image-to-ASCII/requirements.txt
Labels: open-odyssey, dino-accepted

#87 Realtime Face Detection using OpenCV
  realtime face detection/.gitignore
  realtime face detection/LICENSE
  realtime face detection/README.md
  realtime face detection/main.py
  realtime face detection/model/haarcascade_frontalface_default.xml
  realtime face detection/requirements.txt
Labels: open-odyssey, dino-accepted

#99 MCQ generator using machine learning
  MCQ_Generator/README.md
  MCQ_Generator/The Shakespear Enigma.pdf
  MCQ_Generator/The Wonders of Science.docx
  MCQ_Generator/app.py
  MCQ_Generator/index.html
  MCQ_Generator/requirements.txt
  MCQ_Generator/results.html
Labels: open-odyssey, dino-accepted

#88 Static face detection
  Static face detection/haarcascade_frontalface_default.xml
  Static face detection/image.py
  Static face detection/readme.md
  Static face detection/requirements.txt
  Static face detection/students.jpg
Labels: open-odyssey, dino-accepted

#90 Telegram Bot is added
  Telegram_Bot/main.py
  Telegram_Bot/readme.md
  Telegram_Bot/requirements.txt
Labels: open-odyssey, dino-accepted

#89 Salary prediction
  Salary_Prediction/2fde7ad5-b119-40a0-8243-09ad4c7c20f8.png
  Salary_Prediction/README.md
  Salary_Prediction/Salary_Data.csv
  Salary_Prediction/Untitled design.png
  Salary_Prediction/app.py
  Salary_Prediction/model.pkl
  Salary_Prediction/model.py
  Salary_Prediction/request.py
  Salary_Prediction/requirements.txt
  Salary_Prediction/server.py
  Salary_Prediction/static/css/style.css
  Salary_Prediction/templates/index.html
Labels: open-odyssey, dino-accepted

#91 Chess Engine Web Application
  Chess App/.gitignore
  Chess App/board_test.py
  Chess App/chess_engine.py
  Chess App/flask_app.py
  Chess App/readme.md
  Chess App/requirements.txt
  Chess App/static/libs/chessboard/LICENSE.txt
  Chess App/static/libs/chessboard/css/chessboard-0.3.0.css
  Chess App/static/libs/chessboard/css/chessboard-0.3.0.min.css
  Chess App/static/libs/chessboard/img/chesspieces/wikipedia/bB.png
  Chess App/static/libs/chessboard/img/chesspieces/wikipedia/bK.png
  Chess App/static/libs/chessboard/img/chesspieces/wikipedia/bN.png
  Chess App/static/libs/chessboard/img/chesspieces/wikipedia/bP.png
  Chess App/static/libs/chessboard/img/chesspieces/wikipedia/bQ.png
  Chess App/static/libs/chessboard/img/chesspieces/wikipedia/bR.png
  Chess App/static/libs/chessboard/img/chesspieces/wikipedia/wB.png
  Chess App/static/libs/chessboard/img/chesspieces/wikipedia/wK.png
  Chess App/static/libs/chessboard/img/chesspieces/wikipedia/wN.png
  Chess App/static/libs/chessboard/img/chesspieces/wikipedia/wP.png
  Chess App/static/libs/chessboard/img/chesspieces/wikipedia/wQ.png
  Chess App/static/libs/chessboard/img/chesspieces/wikipedia/wR.png
  Chess App/static/libs/chessboard/js/chessboard-0.3.0.js
  Chess App/static/libs/chessboard/js/chessboard-0.3.0.min.js
  Chess App/static/scripts.js
  Chess App/static/style.css
  Chess App/templates/index.html
Labels: open-odyssey, dino-accepted

#124 Added a new encryption project that uses a custom encryption technique
  DNA_cryptography/decrypt.py
  DNA_cryptography/encrypt.py
  DNA_cryptography/readme.md
Labels: open-odyssey, dino-accepted

#93 Dog breed detection using Machine Learning
  Dog_breeds_detection/README.md
  Dog_breeds_detection/app.py
  Dog_breeds_detection/dog_breeds_detection_transfer_learning_fine_tuning_InceptionV3_Model.ipynb
  Dog_breeds_detection/german-shepherd10.jpg
  Dog_breeds_detection/index.html
  Dog_breeds_detection/poodle16.jpg
  Dog_breeds_detection/requirements.txt
  Dog_breeds_detection/rottweiler6.jpg
Labels: open-odyssey, dino-accepted

#95 Student Performance Prediction Using Machine Learning
  Student Performance Prediction/Notebook/1 . EDA STUDENT PERFORMANCE .ipynb
  Student Performance Prediction/Notebook/2. MODEL TRAINING.ipynb
  Student Performance Prediction/Notebook/data/stud.csv
  Student Performance Prediction/README.md
  Student Performance Prediction/app.py
  Student Performance Prediction/artifacts/data.csv
  Student Performance Prediction/artifacts/model.pkl
  Student Performance Prediction/artifacts/preprocessor.pkl
  Student Performance Prediction/artifacts/test.csv
  Student Performance Prediction/artifacts/train.csv
  Student Performance Prediction/catboost_info/catboost_training.json
  Student Performance Prediction/catboost_info/learn/events.out.tfevents
  Student Performance Prediction/catboost_info/learn_error.tsv
  Student Performance Prediction/catboost_info/time_left.tsv
  Student Performance Prediction/logs/09_22_2023_01_17_02.log/09_22_2023_01_17_02.log
  Student Performance Prediction/logs/09_22_2023_01_17_37.log/09_22_2023_01_17_37.log
  Student Performance Prediction/logs/09_22_2023_01_17_38.log/09_22_2023_01_17_38.log
  Student Performance Prediction/logs/09_22_2023_01_18_02.log/09_22_2023_01_18_02.log
  Student Performance Prediction/logs/09_22_2023_01_18_30.log/09_22_2023_01_18_30.log
  Student Performance Prediction/logs/09_22_2023_01_20_28.log/09_22_2023_01_20_28.log
  Student Performance Prediction/logs/09_22_2023_01_20_29.log/09_22_2023_01_20_29.log
  Student Performance Prediction/logs/09_22_2023_01_33_27.log/09_22_2023_01_33_27.log
  Student Performance Prediction/logs/09_22_2023_01_33_28.log/09_22_2023_01_33_28.log
  Student Performance Prediction/logs/09_22_2023_01_33_54.log/09_22_2023_01_33_54.log
  Student Performance Prediction/logs/09_22_2023_01_39_03.log/09_22_2023_01_39_03.log
  Student Performance Prediction/logs/09_22_2023_01_39_05.log/09_22_2023_01_39_05.log
  Student Performance Prediction/requirements.txt
  Student Performance Prediction/runtime.txt
  Student Performance Prediction/setup.py
  Student Performance Prediction/src/__init__.py
  Student Performance Prediction/src/__pycache__/__init__.cpython-37.pyc
  Student Performance Prediction/src/__pycache__/exception.cpython-37.pyc
  Student Performance Prediction/src/__pycache__/logger.cpython-37.pyc
  Student Performance Prediction/src/__pycache__/utils.cpython-37.pyc
  Student Performance Prediction/src/components/__init__.py
  Student Performance Prediction/src/components/data_ingestion.py
  Student Performance Prediction/src/components/data_transformation.py
  Student Performance Prediction/src/components/model_trainer.py
  Student Performance Prediction/src/exception.py
  Student Performance Prediction/src/logger.py
  Student Performance Prediction/src/pipeline/__init__.py
  Student Performance Prediction/src/pipeline/__pycache__/__init__.cpython-37.pyc
  Student Performance Prediction/src/pipeline/__pycache__/predict_pipeline.cpython-37.pyc
  Student Performance Prediction/src/pipeline/predict_pipeline.py
  Student Performance Prediction/src/pipeline/train_pipeline.py
  Student Performance Prediction/src/utils.py
  Student Performance Prediction/static/css/styles.css
  Student Performance Prediction/static/css/styles_home.css
  Student Performance Prediction/templates/home.html
  Student Performance Prediction/templates/index.html
Labels: open-odyssey, dino-accepted

#96 Iris Flower Classification Model
  IRIS Flower classification/README.md
  IRIS Flower classification/app.py
  IRIS Flower classification/forms.py
  IRIS Flower classification/iris-with-answers.csv
  IRIS Flower classification/model.pkl
  IRIS Flower classification/model.py
  IRIS Flower classification/model_import_test.py
  IRIS Flower classification/requirements.txt
  IRIS Flower classification/static/github-logo.png
  IRIS Flower classification/static/image.jpg
  IRIS Flower classification/static/linkedin.png
  IRIS Flower classification/static/main.css
  IRIS Flower classification/templates/layout.html
  IRIS Flower classification/templates/predict.html
  IRIS Flower classification/templates/prediction.html
Labels: open-odyssey, dino-accepted

#98 Handwritten Digit Classification
  Handwritten Digit Recognition/app.py
  Handwritten Digit Recognition/app.yaml
  Handwritten Digit Recognition/checkpoint/mnist.pt
  Handwritten Digit Recognition/config.py
  Handwritten Digit Recognition/readme.md
  Handwritten Digit Recognition/requirements.txt
  Handwritten Digit Recognition/static/jquery.min.js
  Handwritten Digit Recognition/static/screenshot.PNG
  Handwritten Digit Recognition/static/style.css
  Handwritten Digit Recognition/templates/default.html
  Handwritten Digit Recognition/test_app.py
  Handwritten Digit Recognition/torch_serve/index_to_name.json
  Handwritten Digit Recognition/torch_serve/mnist_jit.pt
  Handwritten Digit Recognition/torch_serve/model.py
  Handwritten Digit Recognition/torch_serve/model_store/mnistmodel.mar
  Handwritten Digit Recognition/torch_serve/server.py
  Handwritten Digit Recognition/train.py
  Handwritten Digit Recognition/utils.py
Labels: open-odyssey, dino-accepted

#97 Alzheimer's Disease Detection using Logistic Regression
  Alzheimer's disease's stages prediction/LinearSVM.bin
  Alzheimer's disease's stages prediction/LogisticRegression.bin
  Alzheimer's disease's stages prediction/Procfile
  Alzheimer's disease's stages prediction/app.py
  Alzheimer's disease's stages prediction/dataset-test-train-with-3-features.csv
  Alzheimer's disease's stages prediction/images/3.JPG
  Alzheimer's disease's stages prediction/images/4.JPG
  Alzheimer's disease's stages prediction/images/finalflowdigarm.jpg
  Alzheimer's disease's stages prediction/readme.md
  Alzheimer's disease's stages prediction/requirements.txt
  Alzheimer's disease's stages prediction/runtime.txt
  Alzheimer's disease's stages prediction/scaler.bin
  Alzheimer's disease's stages prediction/templates/css/animate.css
  Alzheimer's disease's stages prediction/templates/css/bootstrap.min.css
  Alzheimer's disease's stages prediction/templates/css/flaticon.css
  Alzheimer's disease's stages prediction/templates/css/font-awesome.min.css
  Alzheimer's disease's stages prediction/templates/css/gijgo.css
  Alzheimer's disease's stages prediction/templates/css/magnific-popup.css
  Alzheimer's disease's stages prediction/templates/css/nice-select.css
  Alzheimer's disease's stages prediction/templates/css/owl.carousel.min.css
  Alzheimer's disease's stages prediction/templates/css/slicknav.css
  Alzheimer's disease's stages prediction/templates/css/style.css
  Alzheimer's disease's stages prediction/templates/css/style.map
  Alzheimer's disease's stages prediction/templates/css/theme-default.css
  Alzheimer's disease's stages prediction/templates/css/theme-default.map
  Alzheimer's disease's stages prediction/templates/css/themify-icons.css
  Alzheimer's disease's stages prediction/templates/index.html
Labels: open-odyssey, dino-accepted

#100 Bank Management System using python
  Bank Management System/.gitattributes
  Bank Management System/Readme.md
  Bank Management System/accounts.data
  Bank Management System/main.py
  Bank Management System/requirements.txt
Labels: open-odyssey, dino-accepted

#101 Book Recommendation System
  Book_Recomender_System/Readme.md
  Book_Recomender_System/books_data.csv
  Book_Recomender_System/main.py
  Book_Recomender_System/requirements.txt
Labels: open-odyssey, dino-accepted

#103 Add a Web Scraper Project
  Web_Scrapper/books.csv
  Web_Scrapper/books.db
  Web_Scrapper/file.py
Labels: open-odyssey, dino-accepted

#107 Contact Management System
  Contact Management System/Readme.md
  Contact Management System/contact.db
  Contact Management System/main.py
  Currency Converter/Readme.md
  Currency Converter/main.py
Labels: open-odyssey, dino-accepted

#108 Update DigitalClock.py
  Digital Clock/DigitalClock.py
Labels: open-odyssey, dino-accepted

#110 Draw a Flower
  Flower Shape/Flower.py
Labels: open-odyssey, dino-accepted

#130 Added AI Tic Tac Toe
  AI-TicTacToe/README.md
  AI-TicTacToe/main.py
Labels: open-odyssey, dino-accepted

#129 added Python Minesweeper Game
  python-minesweeper-game/LICENSE
  python-minesweeper-game/README.md
  python-minesweeper-game/images/original/tile_1.png
  python-minesweeper-game/images/original/tile_2.png
  python-minesweeper-game/images/original/tile_3.png
  python-minesweeper-game/images/original/tile_4.png
  python-minesweeper-game/images/original/tile_5.png
  python-minesweeper-game/images/original/tile_6.png
  python-minesweeper-game/images/original/tile_7.png
  python-minesweeper-game/images/original/tile_8.png
  python-minesweeper-game/images/original/tile_clicked.png
  python-minesweeper-game/images/original/tile_flag.png
  python-minesweeper-game/images/original/tile_mine.png
  python-minesweeper-game/images/original/tile_plain.png
  python-minesweeper-game/images/original/tile_wrong.png
  python-minesweeper-game/images/tile_1.gif
  python-minesweeper-game/images/tile_2.gif
  python-minesweeper-game/images/tile_3.gif
  python-minesweeper-game/images/tile_4.gif
  python-minesweeper-game/images/tile_5.gif
  python-minesweeper-game/images/tile_6.gif
  python-minesweeper-game/images/tile_7.gif
  python-minesweeper-game/images/tile_8.gif
  python-minesweeper-game/images/tile_clicked.gif
  python-minesweeper-game/images/tile_flag.gif
  python-minesweeper-game/images/tile_mine.gif
  python-minesweeper-game/images/tile_plain.gif
  python-minesweeper-game/images/tile_wrong.gif
  python-minesweeper-game/main.py
Labels: open-odyssey, dino-accepted

#131 Added AI Flappy Bird
  AI-Flappy-Bird/main.py
  AI-Flappy-Bird/requirements.txt
Labels: open-odyssey, dino-accepted

#133 Added All in one converters in Python
  All-in-one-converters/README.md
  All-in-one-converters/main.py
Labels: open-odyssey, dino-accepted

#134 Added File Encrypter in Python
  File-Encrypter/README.md
  File-Encrypter/main.py
Labels: open-odyssey, dino-accepted

#132 added Language Translator
  python-language-translator/LICENSE
  python-language-translator/README.md
  python-language-translator/image.png
  python-language-translator/main.py
Labels: open-odyssey, dino-accepted

#126 Face Reco
  Face Recognition Attendance System/.gitignore
  Face Recognition Attendance System/FaceReco.pptx
  Face Recognition Attendance System/app.py
  Face Recognition Attendance System/haarcascade_frontalface_default.xml
  Face Recognition Attendance System/requirements.txt
  Face Recognition Attendance System/static/face_recognition_model.pkl
  Face Recognition Attendance System/static/images/adminlogin.css
  Face Recognition Attendance System/static/images/companylogo.jpg
  Face Recognition Attendance System/static/images/logo2.png
  Face Recognition Attendance System/static/style.css
  Face Recognition Attendance System/templates/admin.html
  Face Recognition Attendance System/templates/adminlogin.html
  Face Recognition Attendance System/templates/home.html
Labels: open-odyssey, dino-accepted

#135 added Car Racing Game
  car-racing-game/LICENSE
  car-racing-game/README.md
  car-racing-game/__init__.py
  car-racing-game/game.py
  car-racing-game/image.png
  car-racing-game/img/__init__.py
  car-racing-game/img/back_ground.jpg
  car-racing-game/img/car.png
  car-racing-game/img/enemy_car_1.png
  car-racing-game/img/enemy_car_2.png
  car-racing-game/requirements.txt
Labels: open-odyssey, dino-accepted

#149 Update Python Calculator codes #40
  Python Calculator/Python Calculator codes.txt
Labels: open-odyssey, dino-accepted

#136 Added IMDB Scraper in Python
  IMDB-Scraper/README.md
  IMDB-Scraper/main.py
  IMDB-Scraper/requirements.txt
Labels: open-odyssey, dino-accepted

#137 added Connect Four
  connect-four/LICENSE
  connect-four/README.md
  connect-four/game.py
  connect-four/icon.png
  connect-four/screenshot.png
Labels: open-odyssey, dino-accepted

#138 added PNG to JPG Converter
  png-to-jpg-converter/LICENSE
  png-to-jpg-converter/README.md
  png-to-jpg-converter/image.png
  png-to-jpg-converter/main.py
Labels: open-odyssey, dino-accepted

#139 Added Website Status Checker in Python
  Website-Status-Checker/README.md
  Website-Status-Checker/main.py
Labels: open-odyssey, dino-accepted

#141 added Bounce - A Classic Brick Breaker Game
  bounce-game/LICENSE
  bounce-game/README.md
  bounce-game/game.py
  bounce-game/image.png
Labels: open-odyssey, dino-accepted

#142 Added Zoom Auto Attend in Python
  Zoom-Auto-Attend/README.md
  Zoom-Auto-Attend/data/meetings.json
  Zoom-Auto-Attend/requirements.txt
  Zoom-Auto-Attend/webdriver/add-driver-here.txt
  Zoom-Auto-Attend/zoomzoom.py
Labels: open-odyssey, dino-accepted

#143 Added RSS News Reader App in Python
  Desktop-Notifier-App/README.md
  Desktop-Notifier-App/main.py
  Desktop-Notifier-App/requirements.txt
Labels: open-odyssey, dino-accepted

#144 Added Spotify Playlist Randomizer in Python
  Spotify-Playlist-Generator/README.md
  Spotify-Playlist-Generator/main.py
  Spotify-Playlist-Generator/requirements.txt
Labels: open-odyssey, dino-accepted

#145 Added Windows Backuper in Python
  BackUp-Drive/README.md
  BackUp-Drive/main.py
Labels: open-odyssey, dino-accepted

#146 Added Habit Tracker in Python
  Habit-Tracker/README.md
  Habit-Tracker/habit_tool.py
  Habit-Tracker/main.py
  Habit-Tracker/requirements.txt
Labels: open-odyssey, dino-accepted

#147 Added Expense Splitter in Python
  Expense-Splitter/README.md
  Expense-Splitter/main.py
Labels: open-odyssey, dino-accepted

#148 Added a BMI Calculator and deleted my previously added file
  BMI CALCULATOR/.idea/BMI CALCULATOR.iml
  BMI CALCULATOR/.idea/inspectionProfiles/profiles_settings.xml
  BMI CALCULATOR/.idea/misc.xml
  BMI CALCULATOR/.idea/modules.xml
  BMI CALCULATOR/Templates/index.html
  BMI CALCULATOR/main.py
Labels: open-odyssey, dino-accepted

#152 Added Hand Detector in Python
  Hand-Detector/main.py
  Hand-Detector/readme.md
  Hand-Detector/requirements.txt
Labels: open-odyssey, dino-accepted

#154 Added Web Cloner in Python
  Web-Cloner/README.md
  Web-Cloner/requirements.txt
  Web-Cloner/webcloner.py
Labels: open-odyssey, dino-accepted

#157 added Mind Maze Adventure
  mind-maze-adventure/LICENSE
  mind-maze-adventure/README.md
  mind-maze-adventure/main.py
Labels: open-odyssey, dino-accepted

#158 Generate And Save Your Password
  password-manager/logo.png
  password-manager/password.py
Labels: open-odyssey, dino-accepted

#163 added Time Travel Adventure Game
  text-based-time-travel-mystery/LICENSE
  text-based-time-travel-mystery/README.md
  text-based-time-travel-mystery/main.py
Labels: open-odyssey, dino-accepted

#165 added Quantum State Puzzle
  quantum-state-puzzle/LICENSE
  quantum-state-puzzle/README.md
  quantum-state-puzzle/main.py
Labels: open-odyssey, dino-accepted

#166 added Typing-Driven RPG Battle Simulator
  typing-driven-rpg-battle-simulator/LICENSE
  typing-driven-rpg-battle-simulator/README.md
  typing-driven-rpg-battle-simulator/main.py
Labels: open-odyssey, dino-accepted

#153 Added Dice Simulator in Python
  Dice-Simulator/README.md
  Dice-Simulator/dice_simulator.py
Labels: open-odyssey, dino-accepted

#156 Weather Forecast App
  Weather Forecast/.idea/.gitignore
  Weather Forecast/.idea/.name
  Weather Forecast/.idea/Weather Forecast.iml
  Weather Forecast/.idea/inspectionProfiles/profiles_settings.xml
  Weather Forecast/.idea/misc.xml
  Weather Forecast/.idea/modules.xml
  Weather Forecast/main.py
  Weather Forecast/templates/index.html
Labels: open-odyssey, dino-accepted

#167 Added Number Game
  Number_Game/number.py
Labels: open-odyssey, waiting room

#172 Mile To Km Converter GUI
  Mile_To_Km/main.py
Labels: open-odyssey, dino-accepted

#171 added School Management System
  school-management-system/LICENSE
  school-management-system/README.md
  school-management-system/main.py
  school-management-system/testdata.db
Labels: open-odyssey, dino-accepted

#60 Light Mode in Digital Clock
  Digital Clock/DigitalClock.py
  continuous-calculator/main.py
Labels: open-odyssey, dino-accepted

#69 Added Rock,Paper,Scissor Game
  Rock,Paper ,Scissor/Rock,paper,scissor-game.py
Labels: open-odyssey, dino-accepted

#182 Automated Birthday Wisher
  Automated_Birthday_Wisher/birthdays.csv
  Automated_Birthday_Wisher/letter_templates/letter_1.txt
  Automated_Birthday_Wisher/letter_templates/letter_2.txt
  Automated_Birthday_Wisher/letter_templates/letter_3.txt
  Automated_Birthday_Wisher/main.py
  Higher_Lower_Game/__pycache__/game_data.cpython-38.pyc
  Higher_Lower_Game/game_data.py
  Higher_Lower_Game/higher_lower.py
  ISS_overhead_notifier/api.py
  Quiz_GUI/card_back.png
  Quiz_GUI/main.py
  Quiz_GUI/question_module.py
  Quiz_GUI/quizbrain.py
  Quiz_GUI/score_manager.py
Labels: open-odyssey

#177 Quiz GUI Application
  Quiz_GUI/card_back.png
  Quiz_GUI/main.py
  Quiz_GUI/question_module.py
  Quiz_GUI/quizbrain.py
  Quiz_GUI/score_manager.py
Labels: open-odyssey

#125 Digital Clock by Saikat in new format
  Digital Clock/DigitalClock.py
  Python Calculator/calculator.py
  password_generator/main.py
Labels: open-odyssey, dino-accepted

#77 Added a word cloud generator script
  Word_Cloud_Generator/README.md
  Word_Cloud_Generator/word_cloud.py
  Word_Cloud_Generator/words.txt
  gpa-calculator/gpa_calculator.py
Labels: open-odyssey, dino-accepted

#179 US-States-Game
  us-states-game/.idea/.gitignore
  us-states-game/.idea/inspectionProfiles/profiles_settings.xml
  us-states-game/.idea/misc.xml
  us-states-game/.idea/modules.xml
  us-states-game/.idea/us-states-game.iml
  us-states-game/50_states.csv
  us-states-game/Missing states.csv
  us-states-game/blank_states_img.gif
  us-states-game/main.py
Labels: open-odyssey, dino-accepted

#181 Coffee-Machine
  coffee-machine/.idea/.gitignore
  coffee-machine/.idea/coffee-machine.iml
  coffee-machine/.idea/inspectionProfiles/profiles_settings.xml
  coffee-machine/.idea/misc.xml
  coffee-machine/.idea/modules.xml
  coffee-machine/main.py
Labels: open-odyssey, dino-accepted
